### ISSUE TITLE
[BUG] lorem-ipsum words can be missed/ignored due to casing

### ISSUE THREAD

**Issue by daephx** [psliwka/vim-dirtytalk#35]
The sample text for the lorem-ipsum script contains uppercase characters that get emitted when rebuilding the word list. Since Vim's spell dictionary is case-sensitive, these words are still marked as incorrect in different flavors or mutations of the lorem paragraph.

This should be an easy fix by adding something like `tr '[:upper:]' '[:lower:]'` to the command pipeline.

I opened a PR for this issue: #34.

**Comment by daephx** [comment]
As a side issue: I use the plugin [friendly-snippets](https://github.com/rafamadriz/friendly-snippets) where they provide a snippet for lorem text, 
and there appears to be a discrepancy in that plugin and this one.

That text contain the string: `adipisicing`, while this plugins example uses `adipiscing`. I can only guess there is slight variations on lorem text, perhaps it's an alternate spelling but that means this word will not be recognized with this plugins current method word list.

I've added this to my spell dictionary for now but is it worth and/or is there a clean way to include this in the `update-lorem-ipsum` script? Just adding the new paragraph would require scrubbing duplicates most likely.

<details>
<summary>Lorem paragraph: provided by <code>vim-dirtytalk</code></summary>

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
```

</details>

<details>
<summary>Lorem paragraph: provided by <code>friendly-snippets</code></summary>

```
Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim
labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi
anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est
aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia
pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit
commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa
proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia
eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim.
Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa
duis.
```

</details>

**Comment by psliwka** [comment]
Good catch, thanks for fixing this! I just merged the fix to master.

> [...] is it reasonable to consider adding the alternate passage to the plugin's update-lorem-ipsum script?

Sounds perfectly reasonable. I pulled this version of lorem-ipsum from Wikipedia, but frankly I have no idea which one is "correct", or whether a "correct" version exists at all (it's not actual Latin AFAIK). But if alternate versions exist in the wild then yeah, I think we want to cover all of them ;)

**Comment by daephx** [comment]
Man, I always just assumed it was "just" Latin. Guess it's been mutated for a few hundred years.

> The lorem ipsum is based on De finibus bonorum et malorum, a Latin text written by Cicero in 45 BC. Typographers and printers have used passages from this work for formatting since the 16th century. Many words have been added or modified over the centuries. As a result, the lorem ipsum is no longer considered Latin, even though it looks a lot like it.

I was playing around with adding the alternate by using some extra commands in the pipeline like `sort | uniq` in an attempt to strip duplicates but didn't get far since the output was removing too many words. I'll play around with it again when I have time.

Glad this could get merged. Thanks!
